import { getViteConfig } from 'astro/config'

export default getViteConfig({
	cacheDir: '.cache', // Vitest will append `/vitest` to this path already.
	// @ts-expect-error - Astro's getViteConfig doesn't expose test config typing
	test: {
		environment: 'node',
		testTimeout: 60000, // 60s
		typecheck: {
			enabled: true,
		},
		// Only the post-build tests. These depend on `dist/` having been
		// generated by `pnpm build`, so this config is only used via
		// `pnpm check:build:post` (after the build step in tests/postbuild.sh).
		include: ['tests/postbuild/**/*.test.ts'],
	},
	json: {
		stringify: false,
	},
})
