import { capturedWalletDataCollection } from '@/tools/wallet-data-collection/data-collection-for-wallet-lib.ts'

import browserData from './rainbow.browser.datacollection.autogenerated.json'
import mobileData from './rainbow.mobile.datacollection.autogenerated.json'

const rainbowDataCollection = capturedWalletDataCollection([browserData, mobileData])

export default rainbowDataCollection
