import { capturedWalletDataCollection } from '@/tools/wallet-data-collection/data-collection-for-wallet-lib.ts'

import browserData from './rainbow.browser.datacollection.autogenerated.json'

const rainbowDataCollection = capturedWalletDataCollection([browserData])

export default rainbowDataCollection
