import * as fs from 'node:fs/promises'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import {
	iconFontStartCharCode,
	maxIconFontChars,
} from '@/tools/icon-font-generator/icon-font-generator-lib'

import {
	type CodebaseEntry,
	CodebaseEntryType,
	commonExclusions,
	crawlCodebase,
	getCrlfFilesFromGit,
	getRepositoryRoot,
	GitIgnoredFiles,
	normalizePath,
	type PathPredicate,
} from './utils/codebase'

/** File extensions that are allowed in the repository. */
const ALLOWED_EXTENSIONS = new Set([
	'.ts',
	'.astro',
	'.svelte',
	'.css',
	'.txt',
	'.md',
	'.mdc',
	'.eot',
	'.ttf',
	'.woff',
	'.woff2',
	'.png',
	'.jpg',
	'.jpeg',
	'.gif',
	'.ico',
	'.svg',
	'.pdf',
	'.sh',
	'.py',
	'.sty',
	'.sha256',
	'.sha512sums',
	'.version',
	'.lock',
	'.Containerfile',
	'.sol',
	'.json',
	'.jsonc',
	'.js',
	'.mjs',
	'.html',
	'.xml',
	'.tsv',
	'.yaml',
	'.toml',
])

/** Filenames that are allowed without a recognized extension. */
const ALLOWED_BARE_FILENAMES = new Set([
	'README',
	'LICENSE',
	'CONTRIBUTING',
	'Makefile',
	'agentsignore',
	'checkpoint',
	'torrc',
	'.editorconfig',
	'.gitattributes',
	'.gitignore',
	'.gitmodules',
	'.prettierignore',
])

describe('codebase integrity', () => {
	describe('all files have Unix line endings', () => {
		const filesWithCrlf = [...getCrlfFilesFromGit(getRepositoryRoot())]

		it('all files have Unix line endings', () => {
			expect(filesWithCrlf, `Files with CRLF line endings: ${filesWithCrlf.join(', ')}`).toEqual([])
		})
	})

	describe('all files have trailing newline', async () => {
		const filesWithoutTrailingNewline: string[] = []
		const svgFilesWithNewline: string[] = []

		await crawlCodebase({
			ignore: [
				// Foundry lockfile, autogenerated without terminating newline.
				'resources/contracts/foundry.lock' as PathPredicate,
				// Husky-generated shims under `.husky/_/` are local-only (not tracked) and often have no trailing newline.
				(path: string): boolean => normalizePath(path).startsWith('.husky/_/'),
			].concat(commonExclusions),
			traversalFn: entry => {
				if (entry.type !== CodebaseEntryType.FILE) {
					return
				}

				if (entry.path.endsWith('.svg')) {
					if (entry.contents.endsWith('\n')) {
						svgFilesWithNewline.push(entry.path)
					}

					return
				}

				if (!entry.contents.endsWith('\n')) {
					filesWithoutTrailingNewline.push(entry.path)
				}
			},
		})

		it('all files have trailing newline', () => {
			expect(
				filesWithoutTrailingNewline,
				`Files without trailing newline:\n\n${filesWithoutTrailingNewline.join('\n')}\n\nPlease add a trailing newline.`,
			).toEqual([])
		})

		it('SVG files do not have trailing newline', () => {
			expect(
				svgFilesWithNewline,
				`SVG files with trailing newline:\n\n${svgFilesWithNewline.join('\n')}\n\nPlease strip the newline.`,
			).toEqual([])
		})
	})

	describe('all files have valid extensions', async () => {
		const filesWithInvalidExtensions: string[] = []

		await crawlCodebase({
			ignore: ['.git', await GitIgnoredFiles()],
			traversalFn: entry => {
				if (entry.type !== CodebaseEntryType.FILE) {
					return
				}

				// Get the basename and extension from the path
				const basename = entry.path.split('/').pop() ?? entry.path
				const dotIndex = basename.lastIndexOf('.')

				// Files with no extension: check against allowed bare filenames
				if (dotIndex === -1 || dotIndex === 0) {
					if (!ALLOWED_BARE_FILENAMES.has(basename)) {
						filesWithInvalidExtensions.push(entry.path)
					}

					return
				}

				// Files with an extension: check against allowed extensions
				const extension = basename.slice(dotIndex)

				if (!ALLOWED_EXTENSIONS.has(extension)) {
					filesWithInvalidExtensions.push(entry.path)
				}
			},
		})

		it('all files have valid extensions', () => {
			expect(
				filesWithInvalidExtensions,
				`Files with invalid extensions:\n\n${filesWithInvalidExtensions.join('\n')}\n\nPlease rename the file, add the extension to the whitelist, or remove the file.`,
			).toEqual([])
		})
	})

	describe('all symlinks are valid', async () => {
		const symlinks: (CodebaseEntry & { type: CodebaseEntryType.SYMLINK })[] = []

		await crawlCodebase({
			ignore: ['.git', 'node_modules'],
			traversalFn: entry => {
				if (entry.type === CodebaseEntryType.SYMLINK) {
					symlinks.push(entry)
				}
			},
		})

		for (const symlink of symlinks) {
			describe(`symlink ${symlink.path}`, () => {
				it('points to valid target', async () => {
					await expect(fs.access(symlink.absoluteTarget)).resolves.toBeUndefined()
				})
				const normalizedRoot = path.resolve(normalizePath(getRepositoryRoot()))

				it('points within the repository', () => {
					const symlinkDir = path.dirname(symlink.path)
					const components = symlink.rawTarget.split(path.sep)

					let currentPath = symlinkDir

					for (const component of components) {
						if (component === '' || component === '.') {
							continue
						}

						currentPath = path.join(currentPath, component)

						const normalizedCurrent = path.resolve(normalizePath(currentPath))

						if (
							normalizedCurrent !== normalizedRoot &&
							!normalizedCurrent.startsWith(normalizedRoot + path.sep) &&
							!normalizedCurrent.startsWith(normalizedRoot + '/')
						) {
							throw new Error(`Symlink ${symlink.path} escapes repository: ${normalizedCurrent}`)
						}
					}
				})
			})
		}
	})

	describe('all files have only ASCII characters and no BOM', async () => {
		// This test exists to avoid attacks leveraging non-visible characters in code
		// to sneak in code execution that contains a malicious payload.

		interface NonAsciiViolation {
			filePath: string
			lineNumber: number
			lineContent: string
			badChars: string[]
		}
		const filesWithNonAscii: NonAsciiViolation[][] = []
		const filesWithBom: string[] = []

		// Any change to the set of characters below should be examined with extreme prejudice.
		const allowedNonAscii = new Set<string>([
			'´',
			'ᵗ',
			'ˢ',
			'°',
			'˚',
			'•',
			'・',
			'·',
			'‑',
			'●',
			'→',
			'←',
			'↗',
			'☠',
			'…',
			'✓',
			'ℹ',
			'↑',
			'⌘',
			'✗',
			'θ',
			'○',
			'▸',
			'—',
			'–',
			'−',
			'─',
			'┌',
			'┐',
			'│',
			'├',
			'┤',
			'┘',
			'└',
			'┼',
			'┬',
			'┃',
			'◄',
			'▼',
			'⚠',
			'‼',
			'ń',
			'‘',
			'’',
			'“',
			'”',
			'×',
			'›',
			'≤',
			'≥',
			'℅',
			'ᵗ',
			'ʰ',
			'↔',
			'‚',
			'„',
			'†',
			'‡',
			'‹',
			'€',
			'™',
			'↓',
			'↕',
			'↖',
			'↘',
			'↙',
			'∞',
			'≈',
			'≠',
			'ə',
			'ẞ',
			'Ỳ',
			'ỳ',
		])

		// Characters used in font files generated from SVG.
		for (let charCodeOffset = 0; charCodeOffset < maxIconFontChars; charCodeOffset++) {
			allowedNonAscii.add(String.fromCodePoint(iconFontStartCharCode + charCodeOffset))
		}

		// Characters used in Monorium Dingbat.
		for (const [charCodeMin, charCodeMax] of [
			[160, 399],
			[536, 567],
			[768, 780],
			[786, 786],
			[806, 808],
			[7808, 7813],
		] as Array<[number, number]>) {
			for (let c = charCodeMin; c <= charCodeMax; c++) {
				allowedNonAscii.add(String.fromCodePoint(c))
			}
		}

		for (const nonAscii of allowedNonAscii) {
			if ([...nonAscii].length !== 1) {
				throw new Error(
					`invalid non-ASCII character list: ${JSON.stringify(nonAscii)} (length: ${[...nonAscii].length})`,
				)
			}
		}
		const emojiSequence = /\p{RGI_Emoji}/gv

		await crawlCodebase({
			ignore: commonExclusions,
			traversalFn: entry => {
				if (entry.type !== CodebaseEntryType.FILE) {
					return
				}

				// Check for BOM (UTF-8 BOM is 0xEFBBBF)
				if (
					entry.raw.length >= 3 &&
					entry.raw[0] === 0xef &&
					entry.raw[1] === 0xbb &&
					entry.raw[2] === 0xbf
				) {
					filesWithBom.push(entry.path)
				}

				const lines = entry.contents.split('\n')
				const violations: NonAsciiViolation[] = []

				for (let i = 0; i < lines.length; i++) {
					const line = lines[i].replaceAll(emojiSequence, '[emoji]')
					const foundNonAscii: string[] = []

					for (const char of line) {
						const codePoint = char.codePointAt(0)

						if (codePoint === undefined) {
							throw new Error(`failed getting codepoint from line ${i} of ${entry.path}`)
						}

						if (codePoint < 127) {
							// Allow Tab (9), Line Feed (10), Carriage Return (13).
							// Carriage return is already filtered in a different test.
							if (codePoint < 32 && codePoint !== 9 && codePoint !== 10 && codePoint !== 13) {
								foundNonAscii.push(`control character (charcode: ${codePoint})`)
							}

							continue
						}

						if (codePoint === 127) {
							foundNonAscii.push('DEL control character (charcode: 127)')
							continue
						}

						if (codePoint === 65533) {
							foundNonAscii.push('replacement character (charcode: 65533, caused by invalid UTF-8)')
							break
						}

						if (allowedNonAscii.has(char)) {
							continue
						}

						foundNonAscii.push(`"${char}" (charcode: ${codePoint})`)
					}

					if (foundNonAscii.length > 0) {
						const lineNumber = i + 1
						const lineContent = line.length > 256 ? line.slice(0, 256) + '...' : line

						violations.push({
							filePath: entry.path,
							lineNumber,
							lineContent,
							badChars: foundNonAscii,
						})

						// Limit to 3 violations per file
						if (violations.length >= 3) {
							break
						}
					}
				}

				if (violations.length > 0) {
					filesWithNonAscii.push(violations)
				}
			},
		})

		it('all files have only ASCII characters', () => {
			const message = filesWithNonAscii
				.map(fileViolations => {
					return (
						fileViolations[0].filePath +
						'\n' +
						fileViolations
							.map(
								v => `  Line ${v.lineNumber}: "${v.lineContent}" (found: ${v.badChars.join(', ')})`,
							)
							.join('\n')
					)
				})
				.join('\n\n')

			expect(
				filesWithNonAscii,
				`Files with non-ASCII characters or invalid UTF-8:\n\n${message}\n\nPlease convert to ASCII only.`,
			).toEqual([])
		})

		it('all files have no BOM', () => {
			expect(
				filesWithBom,
				`Files with BOM (Byte Order Mark):\n\n${filesWithBom.join('\n')}\n\nPlease remove the BOM.`,
			).toEqual([])
		})
	})

	describe('all filenames use consistent naming', async () => {
		/**
		 * Regexes applied to each path component (segment between slashes).
		 * Paths must match at least one.
		 */
		const PATH_COMPONENT_REGEXES = [
			/^\.[a-z0-9]+(\.[a-z0-9]+)*$/, // .dotfiles
			/^[a-z0-9]+([-.][a-z0-9]+)*(\.[a-z0-9]+)*$/, // snake-case
			/^[a-z0-9]+([_.][a-z0-9]+)*(\.[a-z0-9]+)*$/, // snake_case
			/^[a-z0-9]+([A-Z][a-z0-9]*)*(\.[a-z0-9]+)*$/, // camelCase
			/^([A-Z0-9][a-z0-9]*)+(\.[a-z0-9]+)*$/, // PascalCase
			/^\d{4}-\d{2}-\d{2} - [-\w ]+(\.[a-z0-9]+)*$/, // 'YYYY-MM-DD - Something'
		]

		/** Path components that are exempt from the check. */
		const PATH_COMPONENT_WHITELIST = new Set<string>([
			'eternalsafe.Containerfile',
			'[attrGroupId].astro',
			'[walletName]',
		])

		const componentsFailed: string[] = []

		await crawlCodebase({
			ignore: commonExclusions,
			traversalFn: entry => {
				// Skip the root path itself
				if (entry.path === '.' || entry.path === '') {
					return
				}

				const components = entry.path.split('/')

				for (const component of components) {
					if (PATH_COMPONENT_WHITELIST.has(component)) {
						continue
					}

					if (PATH_COMPONENT_REGEXES.every(regex => !regex.test(component))) {
						componentsFailed.push(`${entry.path} (component: ${component})`)
						break
					}
				}
			},
		})

		it('all file paths use consistent naming', () => {
			expect(
				componentsFailed,
				`Paths failing naming consistency check:\n\n${componentsFailed.join('\n')}\n\nPlease rename to snake-case or CamelCase or add to whitelist.`,
			).toEqual([])
		})
	})
})
