import * as fs from 'node:fs/promises'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import {
	type CodebaseEntry,
	CodebaseEntryType,
	commonExclusions,
	crawlCodebase,
	getRepositoryRoot,
	normalizePath,
	type PathPredicate,
} from './utils/codebase'

describe('repo integrity', () => {
	describe('all files have Unix line endings', async () => {
		const filesWithCrlf: string[] = []

		await crawlCodebase({
			ignore: commonExclusions,
			traversalFn: entry => {
				if (entry.type === CodebaseEntryType.FILE && entry.contents.includes('\r\n')) {
					filesWithCrlf.push(entry.path)
				}
			},
		})

		it('all files have Unix line endings', () => {
			expect(filesWithCrlf, `Files with CRLF line endings: ${filesWithCrlf.join(', ')}`).toEqual([])
		})
	})

	describe('all files have trailing newline', async () => {
		const filesWithoutTrailingNewline: string[] = []
		const svgFilesWithNewline: string[] = []

		await crawlCodebase({
			ignore: [
				// Foundry lockfile, autogenerated without terminating newline.
				'resources/contracts/foundry.lock' as PathPredicate,
			].concat(commonExclusions),
			traversalFn: entry => {
				if (entry.type !== CodebaseEntryType.FILE) {
					return
				}

				if (entry.path.endsWith('.svg')) {
					if (entry.contents.endsWith('\n')) {
						svgFilesWithNewline.push(entry.path)
					}

					return
				}

				if (!entry.contents.endsWith('\n')) {
					filesWithoutTrailingNewline.push(entry.path)
				}
			},
		})

		it('all files have trailing newline', () => {
			expect(
				filesWithoutTrailingNewline,
				`Files without trailing newline:\n\n${filesWithoutTrailingNewline.join('\n')}\n\nPlease add a trailing newline.`,
			).toEqual([])
		})

		it('SVG files do not have trailing newline', () => {
			expect(
				svgFilesWithNewline,
				`SVG files with trailing newline:\n\n${svgFilesWithNewline.join('\n')}\n\nPlease strip the newline.`,
			).toEqual([])
		})
	})

	describe('all symlinks are valid', async () => {
		const symlinks: (CodebaseEntry & { type: CodebaseEntryType.SYMLINK })[] = []

		await crawlCodebase({
			ignore: ['.git', 'node_modules'],
			traversalFn: entry => {
				if (entry.type === CodebaseEntryType.SYMLINK) {
					symlinks.push(entry)
				}
			},
		})

		for (const symlink of symlinks) {
			describe(`symlink ${symlink.path}`, () => {
				it('points to valid target', async () => {
					await expect(fs.access(symlink.absoluteTarget)).resolves.toBeUndefined()
				})
				const normalizedRoot = path.resolve(normalizePath(getRepositoryRoot()))

				it('points within the repository', () => {
					const symlinkDir = path.dirname(symlink.path)
					const components = symlink.rawTarget.split(path.sep)

					let currentPath = symlinkDir

					for (const component of components) {
						if (component === '' || component === '.') {
							continue
						}

						currentPath = path.join(currentPath, component)

						const normalizedCurrent = path.resolve(normalizePath(currentPath))

						if (
							normalizedCurrent !== normalizedRoot &&
							!normalizedCurrent.startsWith(normalizedRoot + path.sep) &&
							!normalizedCurrent.startsWith(normalizedRoot + '/')
						) {
							throw new Error(`Symlink ${symlink.path} escapes repository: ${normalizedCurrent}`)
						}
					}
				})
			})
		}
	})

	describe('all files have only ASCII characters', async () => {
		// This test exists to avoid attacks leveraging non-visible characters in code
		// to sneak in code execution that contains a malicious payload.

		interface NonAsciiViolation {
			filePath: string
			lineNumber: number
			lineContent: string
			badChars: string[]
		}
		const filesWithNonAscii: NonAsciiViolation[][] = []

		// Any change to the set of characters below should be examined with extreme prejudice.
		const allowedNonAscii = new Set<string>([
			'´',
			'°',
			'˚',
			'•',
			'・',
			'●',
			'→',
			'↗',
			'☠',
			'…',
			'✓',
			'ℹ',
			'↑',
			'⌘',
			'✗',
			'θ',
			'○',
			'▸',
			'—',
			'–',
			'⚠',
			'‼',
		])

		for (const nonAscii of allowedNonAscii) {
			if (nonAscii.length !== 1) {
				throw new Error('invalid non-ASCII character list')
			}
		}

		await crawlCodebase({
			ignore: [
				// Text and Markdown files are just text content, not code, so they are excluded.
				/^.*\.(txt|md)$/i as PathPredicate,

				// JSON/YAML|TSV files are just structured content, not code, so they are excluded.
				/^.*\.(json|yaml|tsv)$/i as PathPredicate,

				// TEMPORARY EXCLUSION: TypeScript files.
				/^.*\.(ts)$/i as PathPredicate,

				// TEMPORARY EXCLUSION: Astro/Svelte files.
				/^.*\.(astro|svelte)$/i as PathPredicate,
			].concat(commonExclusions),
			traversalFn: entry => {
				if (entry.type !== CodebaseEntryType.FILE) {
					return
				}

				const lines = entry.contents.split('\n')
				const violations: NonAsciiViolation[] = []

				for (let i = 0; i < lines.length; i++) {
					const line = lines[i]
					const foundNonAscii: string[] = []

					for (let j = 0; j < line.length; j++) {
						const charCode = line.charCodeAt(j)

						if (charCode > 127 && !allowedNonAscii.has(line.charAt(j))) {
							foundNonAscii.push(`"${line.charAt(j)}" (charcode: ${charCode})`)
							break
						}
					}

					if (foundNonAscii.length > 0) {
						const lineNumber = i + 1
						const lineContent = line.length > 256 ? line.slice(0, 256) + '...' : line

						violations.push({
							filePath: entry.path,
							lineNumber,
							lineContent,
							badChars: foundNonAscii,
						})

						// Limit to 3 violations per file
						if (violations.length >= 3) {
							break
						}
					}
				}

				if (violations.length > 0) {
					filesWithNonAscii.push(violations)
				}
			},
		})

		it('all files have only ASCII characters', () => {
			const message = filesWithNonAscii
				.map(fileViolations => {
					return (
						fileViolations[0].filePath +
						'\n' +
						fileViolations
							.map(
								v => `  Line ${v.lineNumber}: "${v.lineContent}" (found: ${v.badChars.join(', ')})`,
							)
							.join('\n')
					)
				})
				.join('\n\n')

			expect(
				filesWithNonAscii,
				`Files with non-ASCII characters:\n\n${message}\n\nPlease convert to ASCII only.`,
			).toEqual([])
		})
	})
})
