import { capturedWalletDataCollection } from '@/tools/wallet-data-collection/data-collection-for-wallet-lib.ts'

import browserData from './uniswapWallet.browser.datacollection.autogenerated.json'

const uniswapWalletDataCollection = capturedWalletDataCollection([browserData])

export default uniswapWalletDataCollection
