import * as path from 'node:path'

import { cac } from 'cac'

import { getRepositoryRoot } from '@/tests/utils/codebase'
import { getErrorMessage } from '@/types/errors'

import { type MarkdownImportsConfig, MarkdownImportsGenerator } from './markdown-import-autogen-lib'

/**
 * Maps each auto-generated imports file to the directory of markdown files it
 * should contain imports for.  These directories are scanned recursively.
 *
 * For every directory (and subdirectory) where there is exactly one Markdown
 * file as a direct child, the generated imports file will contain a line mapping
 * the Markdown file path to its `import(... ?raw)` expression.
 */
export const autoGenerated: Record<`/${string}`, `/${string}`> = {
	'/src/autogen/docs.gen.ts': '/resources/docs',
	'/src/autogen/governance.gen.ts': '/governance',
}

// ── CLI ──

try {
	const cli = cac('markdown-imports-autogen')

	cli.option('--mode <mode>', '"check" or "write"').help().version('0.0.1')

	cli.parse(process.argv)

	const rawMode: unknown = cli.options.mode
	const mode = typeof rawMode === 'string' ? rawMode : undefined

	if (!mode || !(mode === 'check' || mode === 'write')) {
		throw new Error('Error: --mode is required and must be "check" or "write"')
	}

	const repoRoot = getRepositoryRoot()

	// Build generator instances from the autoGenerated mapping
	const generators: MarkdownImportsGenerator[] = Object.entries(autoGenerated).map(
		([genFile, sourceDir]) => {
			const absGenPath = path.join(repoRoot, genFile.slice(1))
			const absSourceDir = path.join(repoRoot, sourceDir.slice(1))

			const config: MarkdownImportsConfig = {
				genFilePath: absGenPath,
				sourceDirs: [absSourceDir],
			}

			return new MarkdownImportsGenerator(config)
		},
	)

	// ── Validation pass ──
	const allErrors: string[] = []

	for (const gen of generators) {
		const errors = gen.validate()

		allErrors.push(...errors.map(e => `${gen.genFileRelativePath()}: ${e}`))
	}

	if (allErrors.length > 0) {
		process.stderr.write(allErrors.join('\n') + '\n')
		process.exit(1)
	}

	// ── Check mode ──
	if (mode === 'check') {
		const checks = await Promise.all(
			generators.map(async g => ({ gen: g, upToDate: await g.isUpToDate() })),
		)
		const outdated = checks.filter(r => !r.upToDate).map(r => r.gen)

		if (outdated.length > 0) {
			const cmd = outdated[0].writeCommand()

			process.stderr.write(
				'The following file(s) are out of date:\n' +
					outdated.map(g => '  ' + g.genFileRelativePath()).join('\n') +
					'\n\nRun this command to regenerate:\n  ' +
					cmd +
					'\n',
			)

			process.exit(1)
		}

		process.stderr.write('All markdown import files are up to date.\n')
		process.exit(0)
	}

	// ── Write mode ──
	{
		for (const gen of generators) {
			await gen.write()

			process.stderr.write('Wrote: ' + gen.genFileRelativePath() + '\n')
		}

		process.exit(0)
	}
} catch (error) {
	process.stderr.write('Error: ' + getErrorMessage(error) + '\n')
	process.exit(1)
}
