/** Set of icons mapped to their emoji. */
export const wbIconEmojiSequences = {
	about: 'ℹ️',
	account_abstraction: '👤',
	account_portability: '🧳',
	account_recovery: '🛟',
	account_type: '🪪',
	account_unruggability: '🪚',
	address_resolution: '📇',
	app_isolation: '🏝️',
	browser_integration: '🌐',
	bug: '🐞',
	by_rating: '⭐',
	by_wallet: '👛',
	chain_abstraction: '🌉',
	chain_verification: '⚓',
	checklist: '✅',
	contribute: '🤝',
	dark_light_mode: '🌗',
	discuss: '💬',
	donation: '🎁',
	duress_resistance: '🔧',
	ecosystem: '🌳',
	eip_trackers: '📌',
	faq: '❓',
	fee_transparency: '💸',
	free_and_open_source_license: '❤️',
	funding_transparency: '💰',
	graduate: '🎓',
	hardware_wallet_interoperability: '🧱',
	hardware_wallet_support: '🗝️',
	l1_provider_independence: '🏠',
	multi_address_privacy: '🖇️',
	newsletter: '📰',
	orderflow_transparency: '🔀',
	passkey_verification: '🫆',
	permissions_management: '🔑',
	poo: '💩',
	privacy: '😎',
	privacy_hygiene: '🧼',
	private_token_transfers: '📨',
	question_mark: '❔',
	release_process_transparency: '📦',
	repository: '🐱',
	scam_prevention: '🚨',
	security: '🔒',
	security_audits: '📜',
	security_best_practices: '📋',
	self_sovereignty: '🏰',
	sharpener: '✏️',
	source_visibility: '👀',
	stage_0: '🌱',
	stage_0_5: '🌿',
	stage_1: '🪴',
	stage_2: '🌾',
	stage_none: '🏜️',
	stages: '🌸',
	transaction_batching: '🧺',
	transaction_inclusion: '📡',
	transaction_legibility: '🧾',
	transparency: '🕵️',
	user_privacy: '🕶️',
	wallet_address_privacy: '🔗',
	wallet_browser: '🧩',
	wallet_desktop: '🖥️',
	wallet_embedded: '🧬',
	wallet_hardware: '📟',
	wallet_mobile: '📱',
	wallet_software: '💻',
	wallet_test: '🧪',
} as const

/** Icon ID for WBIcon. */
export type WBIconID = keyof typeof wbIconEmojiSequences

/** Icons that have only a single variant, mapped to that variant. */
export const knownSingleVariantIcons: Partial<Record<WBIconID, string>> = {
	bug: 'simple',
	by_rating: 'simple',
	by_wallet: 'simple',
	checklist: 'simple',
	contribute: 'simple',
	eip_trackers: 'simple',
	poo: 'simple',
	source_visibility: 'simple',
	stages: 'simple',
	discuss: 'complex',
	faq: 'complex',
}
