/** Icon ID for the WBIcon font. */
export type WBIconFontID =
	| 'about'
	| 'account_abstraction'
	| 'account_portability'
	| 'account_recovery'
	| 'account_type'
	| 'account_unruggability'
	| 'address_resolution'
	| 'app_isolation'
	| 'browser_integration'
	| 'chain_abstraction'
	| 'chain_verification'
	| 'discuss'
	| 'duress_resistance'
	| 'ecosystem'
	| 'faq'
	| 'fee_transparency'
	| 'free_and_open_source_license'
	| 'funding_transparency'
	| 'hardware_wallet_interoperability'
	| 'hardware_wallet_support'
	| 'l1_provider_independence'
	| 'multi_address_privacy'
	| 'newsletter'
	| 'orderflow_transparency'
	| 'passkey_verification'
	| 'permissions_management'
	| 'privacy'
	| 'privacy_hygiene'
	| 'private_token_transfers'
	| 'question_mark'
	| 'release_process_transparency'
	| 'repository'
	| 'scam_prevention'
	| 'security'
	| 'security_audits'
	| 'security_best_practices'
	| 'self_sovereignty'
	| 'source_visibility'
	| 'transaction_batching'
	| 'transaction_inclusion'
	| 'transaction_legibility'
	| 'transparency'
	| 'user_privacy'
	| 'wallet_address_privacy'
	| 'wallet_browser'
	| 'wallet_desktop'
	| 'wallet_embedded'
	| 'wallet_hardware'
	| 'wallet_mobile'
	| 'wallet_software'
	| 'wallet_test'

export const iconFontEmoji: Readonly<Record<WBIconFontID, string>> = {
	about: 'ℹ️',
	account_abstraction: '👤',
	account_portability: '🧳',
	account_recovery: '🛟',
	account_type: '🪪',
	account_unruggability: '🪚',
	address_resolution: '📇',
	app_isolation: '🏝️',
	browser_integration: '🌐',
	chain_abstraction: '🌉',
	chain_verification: '⚓',
	discuss: '💬',
	duress_resistance: '🔧',
	ecosystem: '🌳',
	faq: '❓',
	fee_transparency: '💸',
	free_and_open_source_license: '❤️',
	funding_transparency: '💰',
	hardware_wallet_interoperability: '🧱',
	hardware_wallet_support: '🗝️',
	l1_provider_independence: '🏠',
	multi_address_privacy: '🖇️',
	newsletter: '📰',
	orderflow_transparency: '🔀',
	passkey_verification: '🫆',
	permissions_management: '🔑',
	privacy: '😎',
	privacy_hygiene: '🧼',
	private_token_transfers: '📨',
	question_mark: '❔',
	release_process_transparency: '📦',
	repository: '🐱',
	scam_prevention: '🚨',
	security: '🔒',
	security_audits: '📜',
	security_best_practices: '📋',
	self_sovereignty: '🏰',
	source_visibility: '🔍',
	transaction_batching: '🧺',
	transaction_inclusion: '📡',
	transaction_legibility: '🧾',
	transparency: '🕵️',
	user_privacy: '🕶️',
	wallet_address_privacy: '🔗',
	wallet_browser: '🧩',
	wallet_desktop: '🖥️',
	wallet_embedded: '🧬',
	wallet_hardware: '📟',
	wallet_mobile: '📱',
	wallet_software: '💻',
	wallet_test: '🧪',
}
