import { capturedWalletDataCollection } from '@/tools/wallet-data-collection/data-collection-for-wallet-lib.ts'

import browserData from './ambire.browser.datacollection.autogenerated.json'

const ambireDataCollection = capturedWalletDataCollection([browserData])

export default ambireDataCollection
