import globalAnnotations from '@/data/collection/global.annotations.json'
import { type DataCollection } from '@/schema/features/privacy/data-collection'
import type { AtLeastOneVariant, Variant, VariantFeature } from '@/schema/variants'

import { WalletCaptureAnnotations } from './wallet-capture-annotations'
import { type AutoGenerationOptions, WalletCaptureFile } from './wallet-capture-file'

export type AutoGeneratedDataCollection = DataCollection & {
	walletId: string
}

/**
 * Automatically generate `DataCollection` from network capture data.
 */
export function autoGenerateWalletDataCollection({
	walletId,
	data,
	annotations,
}: {
	walletId: string
	data: AtLeastOneVariant<unknown>
	annotations: unknown
}): (options: AutoGenerationOptions) => Promise<VariantFeature<AutoGeneratedDataCollection>> {
	const walletAnnotations = WalletCaptureAnnotations.fromData(
		walletId,
		annotations,
		globalAnnotations,
	)

	return async (options: AutoGenerationOptions) => {
		return Object.fromEntries(
			await Promise.all(
				Object.entries(data)
					.filter(entry => entry !== undefined)
					.map(
						async (
							entry: [Variant, unknown],
						): Promise<[Variant, AutoGeneratedDataCollection | null]> => {
							const variant: Variant = entry[0]

							if (entry[1] === null) {
								return [variant, null]
							}

							const variantData = WalletCaptureFile.fromData(null, entry[1], walletAnnotations)

							return [variant, { walletId, ...(await variantData.toDataCollection(options)) }]
						},
					),
			),
		)
	}
}
