import { type DataCollection } from '@/schema/features/privacy/data-collection'
import type { AtLeastOneVariant, Variant, VariantFeature } from '@/schema/variants'

import { WalletCaptureAnnotations } from './wallet-capture-annotations'
import { type AutoGenerationOptions, WalletCaptureFile } from './wallet-capture-file'

export type AutoGeneratedDataCollection = DataCollection & {
	walletId: string
}

/**
 * Automatically generate `DataCollection` from network capture data.
 */
export function autoGenerateWalletDataCollection({
	walletId,
	data,
	annotations,
}: {
	walletId: string
	data: AtLeastOneVariant<unknown>
	annotations: unknown
}): (options: AutoGenerationOptions) => VariantFeature<AutoGeneratedDataCollection> {
	const walletAnnotations = WalletCaptureAnnotations.fromData(walletId, annotations)

	return (options: AutoGenerationOptions) =>
		Object.fromEntries(
			Object.entries(data)
				.filter(entry => entry !== undefined)
				.map((entry: [Variant, unknown]): [Variant, AutoGeneratedDataCollection | null] => {
					const variant: Variant = entry[0]

					if (entry[1] === null) {
						return [variant, null]
					}

					const variantData = WalletCaptureFile.fromData(null, entry[1], walletAnnotations)

					return [variant, { walletId, ...variantData.toDataCollection(options) }]
				}),
		)
}
