/**
 * Wallet data collection CLI utility. See README.md for usage information.
 *
 */
import cac from 'cac'

import { allEntities } from '@/data/entities'
import { dataCollectionPurpose, userInfoEnums } from '@/schema/features/privacy/data-collection'
import { variantEnum } from '@/schema/variants'
import { WalletType, walletTypes } from '@/schema/wallet-types'
import { trimWhitespacePrefix } from '@/types/utils/text'

import { recordedFlow } from './wallet-capture-file'
import {
	captureOptions,
	deleteCaptureOptions,
	explainRequestOptions,
	globalOptions,
	handleCapture,
	handleCheck,
	handleDeleteCapture,
	handleExplainRequest,
	handleMarkDomain,
	handleMarkFlowUnsupported,
	handleMarkString,
	handleReviewRequests,
	markDomainOptions,
	markFlowUnsupportedOptions,
	markStringOptions,
} from './wallet-data-collection-lib'

// ============================================================================
// CLI Definition
// ============================================================================

const cli = cac('wallet-data-collection')

// Global options
cli
	.option('--id <wallet_id>', 'ID of the wallet (must already exist in Walletbeat)')
	.option('--variant <variant>', `Variant of the wallet: ${variantEnum.items.join(', ')}`)
	.option('--type <type>', `Type of wallet: ${walletTypes.items.join(', ')}`, {
		default: WalletType.SOFTWARE,
	})

// capture subcommand
cli
	.command('capture', 'Capture network traffic for a specific flow')
	.option('--flow <flow>', `Flow to capture: ${recordedFlow.items.join(', ')}`)
	.option('--wallet-addresses <addresses>', 'Wallet addresses being used (comma-separated)')
	.option('--port <port>', 'mitmproxy port', { default: 8080 })
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' capture --flow='IDLE_PRE_INSTALL'",
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' capture --flow='SEND_ETHER' --wallet-addresses='0x123...,0x456...'",
	)
	.action(async options => {
		await handleCapture(captureOptions.process(options))
	})

// delete-capture subcommand
cli
	.command('delete-capture', 'Delete network traffic from a specific session')
	.option('--session <session ID>', 'session ID')
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' delete-capture --session=42",
	)
	.action(async options => {
		await handleDeleteCapture(deleteCaptureOptions.process(options))
	})

// check subcommand
cli
	.command('check', 'Examine capture file and flag missing information needing triage')
	.example("  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' check")
	.action(async options => {
		await handleCheck(globalOptions.process(options))
	})

// mark-flow-unsupported subcommand
cli
	.command('mark-flow-unsupported', 'Mark a flow as not supported by the wallet')
	.option('--flow <flow>', `Flow to mark as unsupported: ${recordedFlow.items.join(', ')}`)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' mark-flow-unsupported --flow='NATIVE_SWAP'",
	)
	.action(async options => {
		await handleMarkFlowUnsupported(markFlowUnsupportedOptions.process(options))
	})

// mark-domain subcommand
cli
	.command('mark-domain', 'Mark a domain and its subdomains as belonging to an entity.')
	.option(
		'--domain <domain>',
		'Domain to assign to an entity. All subdomains will also be matched.',
	)
	.option(
		'--entity <entity ID>',
		'Entity to assign the domain to. Entities must exist in the codebase first.',
	)
	.usage(
		'mark-domain --domain=<domain-pattern> --entity=<entity-id>' +
			trimWhitespacePrefix(`

				Entities must be defined in the codebase first.
				Known entity IDs: ${Object.keys(allEntities).toSorted().join(', ')}
	`),
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' mark-domain --domain='infura.io' --entity='consensys'",
	)
	.action(async options => {
		await handleMarkDomain(markDomainOptions.process(options))
	})

// explain-request subcommand
cli
	.command(
		'explain-request',
		'Mark requests matching selectors as being done for specific purposes',
	)
	.usage(
		"explain-request --domain=example.com [--path=...] [--method=...] --purposes='<purposes>|NOT_WALLET_INITIATED'" +
			trimWhitespacePrefix(`
				Mark requests matching selectors as being done for specific purposes.
				Use \`--purposes=NOT_WALLET_INITIATED\` if these requests were not initiated by the wallet,
				e.g. those generated by the browser or operating system's built-in analytics.

				List of purposes: ${dataCollectionPurpose.items.join(', ')}
			`),
	)
	.option(
		'--domain <domain>',
		'Domain to match (required). Matches domain and all its subdomains. Globs not allowed.',
	)
	.option('--path <path>', 'Path to match. Globs (*) allowed.')
	.option('--method <method>', 'JSON-RPC method to match. Globs (*) allowed.')
	.option(
		'--purposes <purposes>|NOT_WALLET_INITIATED',
		'Comma-separated set of request purposes, or NOT_WALLET_INITIATED if the request was not initiated by the wallet.',
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' explain-request --domain='infura.io' --method='eth_getBalance' --purposes='CHAIN_DATA_LOOKUP'",
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' explain-request --domain='analytics.example.com' --purposes='ANALYTICS'",
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' explain-request --domain='api.example.com' --path='/v1/swap/*' --purposes='SWAP_QUOTE,TRANSACTION_SIMULATION'",
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' explain-request --domain='builtin-spyware-reporting.chrome.google.com' --purposes='NOT_WALLET_INITIATED'",
	)
	.action(async options => {
		await handleExplainRequest(explainRequestOptions.process(options))
	})

// mark-string subcommand
cli
	.command(
		'mark-string',
		'Mark a string as conveying user data and redact it from the network capture.',
	)
	.usage(
		'mark-string --string=<string> --data=<data-type> [--hint=...]' +
			trimWhitespacePrefix(`

				Mark a string as conveying one or more pieces of user data and redact it from the network capture.
				Valid user data types: ${userInfoEnums.items.join(', ')}
			`),
	)
	.option('--string <string>', 'String to mark and redact.')
	.option(
		'--data <data-type>',
		'User data type (comma-separated list if this matches multiples types of user data).',
	)
	.option(
		'--hint <hint>',
		'Hint/explanation as to what the string is; helps understand redacted data.',
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' mark-string --string='GA1.1.1294582759' --data='TRACKING_IDENTIFIER'",
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' mark-string --string='0x1234...' --data='WALLET_ADDRESS'",
	)
	.example(
		"  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' mark-string --string='CodeMonkey1234' --data='X_DOT_COM_ACCOUNT,FARCASTER_ACCOUNT'",
	)
	.action(async options => {
		await handleMarkString(markStringOptions.process(options))
	})

cli
	.command('review-requests', 'Interactively review requests')
	.example("  $ pnpm wallet-data-collection --id='metamask' --variant='BROWSER' review-requests")
	.action(async options => {
		await handleReviewRequests(globalOptions.process(options))
	})

// Help and version
cli.help()
cli.version('0.1.0')

// Parse and handle errors
cli.parse(process.argv, { run: true })

// Show help if no command provided
if (!cli.matchedCommand && !cli.options.help && !cli.options.version) {
	cli.outputHelp()
}
