import { existsSync } from 'node:fs'

import { getMiddlewareHandler } from '@kindspells/astro-shield/core'
import { getGlobalHashes } from '@kindspells/astro-shield/state'
import { defineMiddleware } from 'astro:middleware'
import path from 'path'
import url from 'url'

// SRI options matching the shield integration config in astro.config.mjs.
const sriOptions = () => ({
	allowInlineScripts: 'all' as const,
	allowInlineStyles: 'all' as const,
	enableMiddleware: true,
	enableStatic: true,
	hashesModule: (() => {
		// The middleware can run from different locations depending on the context.
		// Find it by going up the directory stack.
		let projectRoot = path.dirname(url.fileURLToPath(import.meta.url))

		for (let i = 0; i < 10; i++) {
			if (existsSync(path.join(projectRoot, 'astro.config.mjs'))) {
				break
			}

			projectRoot = path.join(projectRoot, '..')
		}

		if (!existsSync(path.join(projectRoot, 'astro.config.mjs'))) {
			throw new Error(
				`Cannot determine project root (started from ${url.fileURLToPath(import.meta.url)})`,
			)
		}

		return path.join(projectRoot, 'src/generated/sriHashes.mjs')
	})(),
	scriptsAllowListUrls: [],
	stylesAllowListUrls: [],
})

/**
 * Type for the SRI hashes module generated by the shield integration.
 */
interface SriHashesModule {
	perResourceSriHashes: {
		scripts: Record<string, string>
		styles: Record<string, string>
	}
}

/**
 * Populate globalHashes from the pre-generated sriHashes.mjs file.
 *
 * Because `enableMiddleware` is `false` in the shield integration config,
 * the Vite plugin that creates the virtual middleware module is NOT
 * registered, which means the shield never populates globalHashes itself.
 * We must do it manually so the middleware handler can look up SRI hashes
 * during static page generation.
 */
async function populateGlobalHashes() {
	const globalHashes = getGlobalHashes()

	try {
		// eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion -- Dynamic import returns `any`; we know the sriHashes.mjs structure
		const importedModule = (await import(
			/* @vite-ignore */ sriOptions().hashesModule
		)) as SriHashesModule

		if (importedModule.perResourceSriHashes) {
			const { perResourceSriHashes } = importedModule

			for (const [key, value] of Object.entries(perResourceSriHashes.scripts)) {
				globalHashes.scripts.set(key, value)
			}

			for (const [key, value] of Object.entries(perResourceSriHashes.styles)) {
				globalHashes.styles.set(key, value)
			}
		}
	} catch {
		// sriHashes.mjs may not exist yet (first build). The shield's
		// astro:build:done hook will generate it, and the next build
		// pass will find the hashes.
	}

	return globalHashes
}

/**
 * Lazily-created middleware handler. The handler is not created until the
 * first request so that `globalHashes` has been populated first.
 */
let _shieldMiddleware: ReturnType<typeof getMiddlewareHandler> | null = null

/**
 * Whether the `shield` middleware should be applied if the request path ends
 * by any of these.
 */
const shouldShieldByExtension: Record<string, boolean> = {
	// HTML and SRI-compatible resources:
	html: true,
	css: true,
	webm: false,
	webp: false,
	png: false,
	ico: false,
	gif: false,
	svg: false,

	// Fonts:
	eot: false,
	ttf: false,
	woff: false,
	woff2: false,

	// Raw text content:
	json: false,
	md: false,
	txt: false,
}

/**
 * Returns whether the `astro-shield` middleware is appropriate for the given endpoint.
 *
 * @param pathName Request path name component (e.g. '/foo/index.html')
 * @returns Whether the request should be shielded, or `null` if unknown.
 */
export function shouldShield(pathName: string): boolean | null {
	if (pathName.endsWith('/')) {
		return true
	}

	if (pathName.match(/\/[^/]+\.[^/]+$/) === null) {
		return true
	}

	const lowerPathName = pathName.toLowerCase()

	for (const [extension, shouldShield] of Object.entries(shouldShieldByExtension)) {
		if (lowerPathName.endsWith('.' + extension)) {
			return shouldShield
		}
	}

	return null
}

/**
 * Middleware that wraps the `astro-shield` SRI handler so it is skipped for
 * endpoints that serve binary files (images, etc). This avoids triggering
 * a bug in the `astro-shield` middleware which calls `.text()` on all
 * response data regardless of Content-type, corrupting data when not
 * dealing with unicode.
 */
export const onRequest = defineMiddleware(async (context, next) => {
	const shouldBeShielded = shouldShield(context.url.pathname)

	if (shouldBeShielded === null) {
		throw new Error(
			`Unsure if request for '${context.url.pathname}' should be shielded; please update src/middleware.ts.`,
		)
	}

	if (!shouldBeShielded) {
		return next()
	}

	if (!_shieldMiddleware) {
		await populateGlobalHashes()
		_shieldMiddleware = getMiddlewareHandler(console, getGlobalHashes(), sriOptions())
	}

	return await _shieldMiddleware(context, () => next())
})
