import { capturedWalletDataCollection } from '@/tools/wallet-data-collection/data-collection-for-wallet-lib.ts'

import browserData from './rabby.browser.datacollection.autogenerated.json'

const rabbyDataCollection = capturedWalletDataCollection([browserData])

export default rabbyDataCollection
