import { capturedWalletDataCollection } from '@/tools/wallet-data-collection/data-collection-for-wallet-lib.ts'

import browserData from './metamask.browser.datacollection.autogenerated.json'

const metamaskDataCollection = capturedWalletDataCollection([browserData])

export default metamaskDataCollection
