name: Check

on:
  push: {}
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - review_requested

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Check – Astro
            command: pnpm run check:astro
          - name: Test – Vitest
            command: pnpm run check:vitest
          - name: Lint – ESLint
            command: pnpm run check:lint
          - name: Format – Prettier
            command: pnpm run check:syntax
          - name: Spell check – CSpell
            command: pnpm run check:spelling:quiet
          - name: Other checks
            command: pnpm run check:misc
          - name: Build – Astro
            command: pnpm run check:build:post:quiet
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9
      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}
