name: Run code checks
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install packageManager
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Run checks
        run: pnpm check:all
