name: Deploy site via Edgeserver
on:
  push:
    branches:
      - beta
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install packageManager
        uses: pnpm/action-setup@v4
      - name: Install Project Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Edgeserver Upload
        uses: v3xlabs/edgeserver-upload@v0.1.2-pre.4
        with:
          app_id: '422130713911889920'
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGE_TOKEN }}
          directory: dist
          context: true
      - name: Edgeserver v0.2 Upload
        uses: v3xlabs/edgeserver-upload@v0.2.1-pre.4
        with:
          site_id: s_305c36a033
          server: https://edgeserver.dev/api
          token: ${{ secrets.EDGE_TOKEN2 }}
          directory: dist
          context: true
